// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcbmqlkejoejfrouoqfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjYm1xbGtlam9lamZyb3VvcWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1OTE5MDMsImV4cCI6MjA2MjE2NzkwM30.jZUyt7SnShGDWGj-KjOgrSQc23Wcrddrh7g-SGw2Zy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);